batch_size: 64
data:
  audio: data/dev/wav.csv
  class_indice_file: data/metadata/class_label_indices.txt
  label: data/dev/label.csv
  stratified: true
dataloader_args:
  batch_size: 64
  num_workers: 1
early_stop: 10
epochs: 100
loss: BceLoss
model:
  args:
    sample_rate: 44100
  type: Crnn5
num_workers: 2
optimizer:
  args:
    lr: 0.001
  type: AdamW
outputpath: experiments/
scheduler_args:
  factor: 0.1
  patience: 3
