data:
    audio: data/dev/wav.csv
    label: data/dev/label.csv
    class_indice_file: data/metadata/class_label_indices.txt
    augment_type: time_shift
    stratified: TRUE
    
dataloader_args:
    batch_size: 64
    num_workers: 1

optimizer:
    type: AdamW
    args:
        lr: 0.001

epochs: 100 
early_stop: 10
model:
    type: Crnn5
    args:
        sample_rate: 44100

outputpath: experiments/

